# Generated by Django 3.2.8 on 2021-10-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_lives_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Nellis', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
