# Generated by Django 3.2.8 on 2021-10-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('tcto', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tail_number', models.CharField(max_length=10)),
                ('mods', models.ManyToManyField(blank=True, to='Aircraft.Mod')),
            ],
        ),
    ]
