# Generated by Django 3.2.8 on 2021-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='mods',
            field=models.ManyToManyField(blank=True, null=True, to='Aircraft.Mod'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
