# Generated by Django 3.2.8 on 2021-10-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aircraft', '0003_auto_20211017_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='mods',
            field=models.ManyToManyField(blank=True, to='Aircraft.Mod'),
        ),
    ]
