# Generated by Django 3.2.8 on 2021-10-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_discovered', models.DateTimeField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aircraft.aircraft')),
            ],
        ),
    ]
