# Generated by Django 3.2.8 on 2021-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancy',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='date_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
