# Generated by Django 3.2.8 on 2021-10-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0002_auto_20211016_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancy',
            name='date_discovered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='date_resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
