# Generated by Django 3.2.8 on 2021-10-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aircraft', '0004_alter_aircraft_mods'),
        ('discrepancies', '0005_alter_discrepancy_aircraft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancy',
            name='aircraft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aircraft.aircraft'),
        ),
    ]
