# Generated by Django 3.2.8 on 2021-10-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
        ('discrepancies', '0006_alter_discrepancy_aircraft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancy',
            name='discovered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.profile'),
        ),
    ]
