# Generated by Django 3.2.8 on 2021-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0007_discrepancy_discovered_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discrepancy',
            options={'ordering': ['-date_discovered']},
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='occurrences',
            field=models.IntegerField(default=0),
        ),
    ]
