# Generated by Django 3.2.8 on 2021-10-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0008_auto_20211018_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discrepancy',
            options={'ordering': ['date_resolved', '-occurrences', '-date_discovered']},
        ),
    ]
